### PR TITLE
Added argument parser and modified gitignore to ignore .pth files

### PR DESCRIPTION
**Pull request by Thirunayan22**
The argument parser was added to specify the model path and image path in a more readable manner in the infer.py file.
Capture

### CODE REVIEW

**Comment by phamquiluan** [comment]
Thank you for your contribution! Could you please help me to remove the images and update the infer command on the README please :pray:

**Comment by Thirunayan22** [comment]
Sure, but what images do you mean?

**Comment by phamquiluan** [comment]
@Thirunayan22 the output images in maskrcnn/output/, I think that is your results right ?

**Comment by Thirunayan22** [comment]
Yes

**Comment by Thirunayan22** [comment]
I have removed the images and updated the Readme

**Comment by phamquiluan** [comment]
@Thirunayan22 
Please remove the old command. There are two commands in the README could you see ?
image

**Review by phamquiluan — APPROVED** [review]

**Pull request merged**
